name: Go CI
on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.12]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
        # fetch all tags
        fetch-depth: 0    

    - name: Build
      run: go build -v -ldflags "-X github.com/whalebrew/whalebrew/version.Version=$(git describe --always --tags --dirty)" -o whalebrew-${{ matrix.os}} .
    
    - name: Ensure binary works
      run: ./whalebrew-${{ matrix.os}} version

    - uses: actions/upload-artifact@v2
      with:
        name: whalebrew-${{ matrix.os}}
        path: whalebrew-${{ matrix.os}}

    - name: run tests
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required